# Generated by Django 4.1.7 on 2023-03-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0002_rename_member_laptop'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
