# Generated by Django 4.1.7 on 2023-03-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0003_laptop_joined_date_laptop_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='laptop_brand',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
