# Generated by Django 4.1.7 on 2023-03-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0004_laptop_laptop_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='display_condition',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='laptop_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='laptop_serial',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='motherboard_condition',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor_age',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='speed',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
