# Generated by Django 4.1.7 on 2023-03-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0005_laptop_display_condition_laptop_laptop_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='joined_date',
            new_name='report_date',
        ),
    ]
