# Generated by Django 4.1.7 on 2023-03-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0006_rename_joined_date_laptop_report_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('match_string', models.CharField(max_length=255)),
                ('kpi_score', models.IntegerField(null=True)),
            ],
        ),
    ]
