# Generated by Django 4.1.7 on 2023-03-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0007_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='total_kpi_score',
            field=models.IntegerField(null=True),
        ),
    ]
