# Generated by Django 4.1.7 on 2023-03-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap', '0008_laptop_total_kpi_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
